const _ = require('lodash')
const titles =
[ { title: 'Ser', epic: false, id: 1 },
  { title: 'Maester', epic: false, id: 2 },
  { title: 'Prince', epic: false, id: 3 },
  { title: 'Protector of the Realm', epic: true, id: 4 },
  { title: 'Prince Regent', epic: false, id: 5 },
  { title: 'King of the Andals, the Rhoynar and the First Men', epic: true, id: 6 },
  { title: 'Lord of the Seven Kingdoms', epic: true, id: 7 },
  { title: 'Lord of Dragonstone', epic: true, id: 8 },
  { title: 'Priest', epic: false, id: 9 },
  { title: 'Captain of the Golden Storm', epic: true, id: 10 },
  { title: 'King of the Andals, the Rhoynar, and the First Men', epic: true, id: 11 },
  { title: 'Septa', epic: false, id: 12 },
  { title: 'Queen of the Iron Islands', epic: true, id: 13 },
  { title: 'Lord of Brightwater', epic: true, id: 14 },
  { title: 'Lady of Highgarden', epic: false, id: 15 },
  { title: 'Lord of Brightwater', epic: true, id: 16 },
  { title: 'Hand of the King', epic: true, id: 17 },
  { title: 'Lady', epic: false, id: 18 },
  { title: 'Queen', epic: true, id: 19 },
  { title: 'Lord', epic: false, id: 20 },
  { title: 'Lord Commander of the Kingsguard', epic: true, id: 21 },
  { title: 'Lord of Tarbeck Hall', epic: false, id: 22 },
  { title: 'Lord of the Tides', epic: true, id: 23 },
  { title: 'Master of Driftmark', epic: true, id: 24 },
  { title: 'Admiral', epic: false, id: 25 },
  { title: 'Master of ships', epic: false, id: 26 },
  { title: 'Lady of Winterfell', epic: true, id: 27 },
  { title: 'Lady of Blackcrown', epic: true, id: 28 },
  { title: 'Iron King', epic: true, id: 29 },
  { title: 'King of the Isles and the North', epic: true, id: 30 },
  { title: 'King of Salt and Rock', epic: true, id: 31 },
  { title: 'Son of the Sea Wind', epic: false, id: 32 },
  { title: 'Lord Reaper of Pyke', epic: true, id: 33 },
  { title: 'The Greyjoy', epic: false, id: 34 },
  { title: 'Captain of the Great Kraken', epic: false, id: 35 },
 { title: 'Septon', epic: false, id: 36 },
 { title: 'Brother', epic: false, id: 37 },
 { title: 'High Septon', epic: true, id: 38 },
 { title: 'His High Holiness', epic: true, id: 39 },
 { title: 'Father of the Faithful', epic: false, id: 40 },
 { title: 'Voice of the Seven on Earth', epic: false, id: 41 },
 { title: 'Queen of the Seven Kingdoms', epic: true, id: 42 },
 { title: 'Septa', epic: false, id: 43 },
 { title: 'Lord of Casterly Rock', epic: true, id: 44 },
 { title: 'Shield of Lannisport', epic: false, id: 45 },
 { title: 'Warden of the West', epic: false, id: 46 },
 { title: 'Hand of the King', epic: false, id: 47 },
 { title: 'Savior of the City of King\'s Landing', epic: true, id: 48 },
 { title: 'Ser', epic: false, id: 49 },
 { title: 'Commander of the City Watch', epic: false, id: 50 },
 { title: 'Lord Commander of the Kingsguard', epic: true, id: 51 },
 { title: 'King of All Westeros', epic: true, id: 52 },
 { title: 'Shield of His People', epic: true, id: 53 },
 { title: 'King of the Andals, the Rhoynar and the First Men', epic: true, id: 54 },
 { title: 'Lord of the Seven Kingdoms', epic: true, id: 55 },
 { title: 'Protector of the Realm', epic: true, id: 56 },
 { title: 'Lady of Dragonstone', epic: true, id: 57 },
 { title: 'Prince', epic: false, id: 58 },
 { title: 'Lady', epic: false, id: 59 } ]

export function getRandomTitle () {
   let randomIndex = _.random(0, titles.length);
   return titles[randomIndex];
 }
